require('dotenv').config();
const express=require('express');
const cors=require('cors');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const fs=require('fs');
const path=require('path');
const {Pool}=require('pg');

const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_IN_PRODUCTION';
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});

app.use(cors({origin:process.env.CORS_ORIGIN||'*'}));
app.use(express.json({limit:'6mb'}));
app.use(express.urlencoded({extended:true}));
app.use(express.static(path.join(__dirname,'public')));

const schema=fs.readFileSync(path.join(__dirname,'db','schema.sql'),'utf8');
const slugify=s=>String(s||'').trim().toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-+|-+$/g,'')||'item';
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const money=v=>Math.round(num(v));
function sign(u){return jwt.sign({id:u.id,role:u.role},JWT_SECRET,{expiresIn:'30d'});}
function auth(req,res,next){try{const raw=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!raw)throw Error();req.user=jwt.verify(raw,JWT_SECRET);next();}catch{res.status(401).json({error:'UNAUTHORIZED',message:'نیاز به ورود دارید.'});}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'FORBIDDEN',message:'دسترسی مدیر لازم است.'});next();}
async function q(sql,args=[]){return pool.query(sql,args);}
function fail(res,e){console.error(e);res.status(500).json({error:'SERVER_ERROR',message:'خطای داخلی سرور.'});}

app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin','index.html')));
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,database:true});}catch(e){res.status(503).json({ok:false,database:false});}});

// ---------- Authentication ----------
app.post('/api/admin/login',async(req,res)=>{try{
 const {username,password}=req.body||{}; if(!username||!password)return res.status(400).json({error:'نام کاربری و رمز عبور الزامی است.'});
 const r=await q("SELECT * FROM users WHERE phone=$1 AND role='admin' AND active=true LIMIT 1",[String(username).trim()]);
 if(!r.rowCount||!await bcrypt.compare(String(password),r.rows[0].password_hash||''))return res.status(401).json({error:'نام کاربری یا رمز عبور اشتباه است.'});
 const u=r.rows[0];res.json({token:sign(u),user:{id:u.id,name:u.name,phone:u.phone,role:u.role}});
}catch(e){fail(res,e);}});
app.post('/api/auth/register',async(req,res)=>{try{const {name,phone,password}=req.body||{};if(!name||!phone||!password)return res.status(400).json({error:'نام، موبایل و رمز الزامی است.'});if(String(password).length<6)return res.status(400).json({error:'رمز عبور حداقل ۶ کاراکتر باشد.'});const e=await q('SELECT id FROM users WHERE phone=$1',[phone]);if(e.rowCount)return res.status(409).json({error:'این شماره قبلاً ثبت شده است.'});const hash=await bcrypt.hash(password,12);const r=await q("INSERT INTO users(name,phone,password_hash,role) VALUES($1,$2,$3,'customer') RETURNING id,name,phone,role",[name,phone,hash]);res.status(201).json({user:r.rows[0],token:sign(r.rows[0])});}catch(e){fail(res,e);}});
app.post('/api/auth/login',async(req,res)=>{try{const {phone,password}=req.body||{};const r=await q("SELECT * FROM users WHERE phone=$1 AND active=true LIMIT 1",[phone]);if(!r.rowCount||!await bcrypt.compare(password,r.rows[0].password_hash||''))return res.status(401).json({error:'شماره موبایل یا رمز عبور اشتباه است.'});const u=r.rows[0];res.json({user:{id:u.id,name:u.name,phone:u.phone,role:u.role},token:sign(u)});}catch(e){fail(res,e);}});
app.get('/api/me',auth,async(req,res)=>{try{const r=await q('SELECT id,name,phone,role,active,created_at FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND'});res.json(r.rows[0]);}catch(e){fail(res,e);}});

// ---------- Public catalog ----------
app.get('/api/store',async(req,res)=>{try{const [s,c,p,f]=await Promise.all([q("SELECT key,value FROM settings WHERE key IN ('store_name','store_subtitle','phone','address','shipping_fee','min_order')"),q('SELECT * FROM categories WHERE active=true ORDER BY sort_order,name'),q(`SELECT p.*,c.name category_name,c.slug category_slug,COALESCE(d.price,p.price) daily_price FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN LATERAL (SELECT price FROM daily_prices WHERE product_id=p.id ORDER BY price_date DESC,created_at DESC LIMIT 1)d ON true WHERE p.active=true ORDER BY p.featured DESC,p.created_at DESC`),q("SELECT * FROM festivals WHERE active=true AND (start_at IS NULL OR start_at<=NOW()) AND (end_at IS NULL OR end_at>=NOW()) ORDER BY created_at DESC")]);res.json({settings:Object.fromEntries(s.rows.map(x=>[x.key,x.value])),categories:c.rows,products:p.rows,festivals:f.rows});}catch(e){fail(res,e);}});
app.get('/api/categories',async(req,res)=>{try{res.json((await q('SELECT * FROM categories WHERE active=true ORDER BY sort_order,name')).rows);}catch(e){fail(res,e);}});
app.get('/api/products',async(req,res)=>{try{const {category,search,featured}=req.query,a=[];const w=['p.active=true'];if(category){a.push(category);w.push(`c.slug=$${a.length}`);}if(search){a.push(`%${search}%`);w.push(`p.name ILIKE $${a.length}`);}if(featured==='true')w.push('p.featured=true');res.json((await q(`SELECT p.*,c.name category_name,c.slug category_slug,COALESCE(d.price,p.price) daily_price FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN LATERAL (SELECT price FROM daily_prices WHERE product_id=p.id ORDER BY price_date DESC,created_at DESC LIMIT 1)d ON true WHERE ${w.join(' AND ')} ORDER BY p.featured DESC,p.created_at DESC`,a)).rows);}catch(e){fail(res,e);}});
app.get('/api/products/:id',async(req,res)=>{try{const r=await q(`SELECT p.*,c.name category_name,c.slug category_slug,COALESCE(d.price,p.price) daily_price FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN LATERAL (SELECT price FROM daily_prices WHERE product_id=p.id ORDER BY price_date DESC,created_at DESC LIMIT 1)d ON true WHERE p.id=$1 AND p.active=true`,[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'محصول پیدا نشد.'});res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.get('/api/daily-prices',async(req,res)=>{try{res.json((await q(`SELECT DISTINCT ON (d.product_id) d.*,p.name product_name,p.unit,p.image_url FROM daily_prices d JOIN products p ON p.id=d.product_id WHERE p.active=true ORDER BY d.product_id,d.price_date DESC,d.created_at DESC`)).rows);}catch(e){fail(res,e);}});
app.get('/api/festivals',async(req,res)=>{try{res.json((await q("SELECT * FROM festivals WHERE active=true AND (start_at IS NULL OR start_at<=NOW()) AND (end_at IS NULL OR end_at>=NOW()) ORDER BY created_at DESC")).rows);}catch(e){fail(res,e);}});

// ---------- Customer addresses/cart/orders ----------
app.get('/api/addresses',auth,async(req,res)=>{try{res.json((await q('SELECT * FROM addresses WHERE user_id=$1 ORDER BY created_at DESC',[req.user.id])).rows);}catch(e){fail(res,e);}});
app.post('/api/addresses',auth,async(req,res)=>{try{const x=req.body||{};if(!x.recipientName||!x.phone||!x.city||!x.address)return res.status(400).json({error:'اطلاعات آدرس کامل نیست.'});const r=await q('INSERT INTO addresses(user_id,title,recipient_name,phone,province,city,address,postal_code) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[req.user.id,x.title||'آدرس اصلی',x.recipientName,x.phone,x.province||null,x.city,x.address,x.postalCode||null]);res.status(201).json(r.rows[0]);}catch(e){fail(res,e);}});
async function cartId(userId){let r=await q('SELECT id FROM carts WHERE user_id=$1',[userId]);if(!r.rowCount)r=await q('INSERT INTO carts(user_id) VALUES($1) RETURNING id',[userId]);return r.rows[0].id;}
app.get('/api/cart',auth,async(req,res)=>{try{const id=await cartId(req.user.id);const r=await q(`SELECT ci.product_id,ci.quantity,p.name,p.price,p.compare_price,p.image_url,p.unit,p.stock,COALESCE(d.price,p.price) daily_price FROM cart_items ci JOIN products p ON p.id=ci.product_id LEFT JOIN LATERAL (SELECT price FROM daily_prices WHERE product_id=p.id ORDER BY price_date DESC,created_at DESC LIMIT 1)d ON true WHERE ci.cart_id=$1 ORDER BY p.name`,[id]);res.json({cart_id:id,items:r.rows});}catch(e){fail(res,e);}});
app.post('/api/cart/items',auth,async(req,res)=>{try{const {productId,quantity}=req.body||{};if(!productId||num(quantity)<=0)return res.status(400).json({error:'تعداد نامعتبر است.'});const id=await cartId(req.user.id);const p=await q('SELECT stock,active FROM products WHERE id=$1',[productId]);if(!p.rowCount||!p.rows[0].active)return res.status(404).json({error:'محصول موجود نیست.'});if(num(quantity)>num(p.rows[0].stock))return res.status(400).json({error:'موجودی کافی نیست.'});await q('INSERT INTO cart_items(cart_id,product_id,quantity) VALUES($1,$2,$3) ON CONFLICT(cart_id,product_id) DO UPDATE SET quantity=EXCLUDED.quantity',[id,productId,num(quantity)]);await q('UPDATE carts SET updated_at=NOW() WHERE id=$1',[id]);res.json({ok:true});}catch(e){fail(res,e);}});
app.put('/api/cart/items/:productId',auth,async(req,res)=>{try{const id=await cartId(req.user.id),qty=num(req.body?.quantity);if(qty<=0){await q('DELETE FROM cart_items WHERE cart_id=$1 AND product_id=$2',[id,req.params.productId]);}else{await q('UPDATE cart_items SET quantity=$1 WHERE cart_id=$2 AND product_id=$3',[qty,id,req.params.productId]);}res.json({ok:true});}catch(e){fail(res,e);}});
app.delete('/api/cart/items/:productId',auth,async(req,res)=>{try{await q('DELETE FROM cart_items WHERE cart_id=$1 AND product_id=$2',[await cartId(req.user.id),req.params.productId]);res.json({ok:true});}catch(e){fail(res,e);}});
app.post('/api/orders',auth,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const settings=await client.query("SELECT key,value FROM settings WHERE key IN ('shipping_fee','min_order')");const cfg=Object.fromEntries(settings.rows.map(x=>[x.key,x.value]));const cart=await client.query('SELECT id FROM carts WHERE user_id=$1',[req.user.id]);if(!cart.rowCount)throw Error('EMPTY');const items=await client.query(`SELECT ci.product_id,ci.quantity,p.name,p.price,p.stock,COALESCE(d.price,p.price) final_price FROM cart_items ci JOIN products p ON p.id=ci.product_id LEFT JOIN LATERAL (SELECT price FROM daily_prices WHERE product_id=p.id ORDER BY price_date DESC,created_at DESC LIMIT 1)d ON true WHERE ci.cart_id=$1 AND p.active=true FOR UPDATE`,[cart.rows[0].id]);if(!items.rowCount)throw Error('EMPTY');let subtotal=0;for(const x of items.rows){if(num(x.quantity)>num(x.stock))throw Error('STOCK');subtotal+=money(x.final_price)*num(x.quantity);}if(num(cfg.min_order)>0&&subtotal<num(cfg.min_order))throw Error('MIN');const shipping=num(req.body?.shipping)||num(cfg.shipping_fee);const total=subtotal+shipping;const o=await client.query(`INSERT INTO orders(user_id,address_id,status,payment_status,subtotal,shipping,total,note) VALUES($1,$2,'pending','unpaid',$3,$4,$5,$6) RETURNING *`,[req.user.id,req.body?.addressId||null,subtotal,shipping,total,req.body?.note||null]);for(const x of items.rows){const line=money(x.final_price)*num(x.quantity);await client.query('INSERT INTO order_items(order_id,product_id,product_name,unit_price,quantity,line_total) VALUES($1,$2,$3,$4,$5,$6)',[o.rows[0].id,x.product_id,x.name,money(x.final_price),num(x.quantity),line]);await client.query('UPDATE products SET stock=stock-$1,updated_at=NOW() WHERE id=$2',[num(x.quantity),x.product_id]);await client.query("INSERT INTO inventory_transactions(product_id,quantity,type,note) VALUES($1,$2,'sale',$3)",[x.product_id,-num(x.quantity),'سفارش '+o.rows[0].id]);}await client.query('DELETE FROM cart_items WHERE cart_id=$1',[cart.rows[0].id]);await client.query('COMMIT');res.status(201).json(o.rows[0]);}catch(e){await client.query('ROLLBACK');const msg=e.message==='STOCK'?'موجودی کافی نیست.':e.message==='MIN'?'حداقل مبلغ سفارش رعایت نشده است.':e.message==='EMPTY'?'سبد خرید خالی است.':'ثبت سفارش انجام نشد.';res.status(400).json({error:msg});}finally{client.release();}});
app.get('/api/orders',auth,async(req,res)=>{try{res.json((await q(`SELECT o.*,a.city,a.address FROM orders o LEFT JOIN addresses a ON a.id=o.address_id WHERE o.user_id=$1 ORDER BY o.created_at DESC`,[req.user.id])).rows);}catch(e){fail(res,e);}});
app.get('/api/orders/:id',auth,async(req,res)=>{try{const o=await q('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!o.rowCount)return res.status(404).json({error:'سفارش پیدا نشد.'});const items=await q('SELECT * FROM order_items WHERE order_id=$1 ORDER BY id',[req.params.id]);res.json({order:o.rows[0],items:items.rows});}catch(e){fail(res,e);}});

// ---------- Admin dashboard ----------
app.get('/api/admin/dashboard',auth,admin,async(req,res)=>{try{const [counts,sales,recent,low]=await Promise.all([q(`SELECT (SELECT COUNT(*) FROM products WHERE active=true) products,(SELECT COUNT(*) FROM users WHERE role='customer' AND active=true) customers,(SELECT COUNT(*) FROM orders) orders,(SELECT COUNT(*) FROM orders WHERE status='pending') pending_orders,(SELECT COUNT(*) FROM festivals WHERE active=true) festivals`),q("SELECT COALESCE(SUM(total),0) sales,COUNT(*) orders FROM orders WHERE created_at::date=CURRENT_DATE AND status<>'cancelled'"),q(`SELECT o.id,o.total,o.status,o.created_at,u.name customer_name,u.phone FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 8`),q('SELECT id,name,stock,min_stock,unit FROM products WHERE active=true AND stock<=min_stock ORDER BY stock ASC LIMIT 8')]);res.json({...counts.rows[0],today_sales:sales.rows[0].sales,today_orders:sales.rows[0].orders,recent_orders:recent.rows,low_stock:low.rows});}catch(e){fail(res,e);}});

// ---------- Admin products/categories ----------
app.get('/api/admin/products',auth,admin,async(req,res)=>{try{res.json((await q(`SELECT p.*,c.name category_name,COALESCE(d.price,p.price) daily_price FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN LATERAL (SELECT price FROM daily_prices WHERE product_id=p.id ORDER BY price_date DESC,created_at DESC LIMIT 1)d ON true ORDER BY p.created_at DESC`)).rows);}catch(e){fail(res,e);}});
app.post('/api/admin/products',auth,admin,async(req,res)=>{try{const x=req.body||{};if(!x.name)return res.status(400).json({error:'نام محصول الزامی است.'});let s=slugify(x.name),i=1;while((await q('SELECT 1 FROM products WHERE slug=$1',[s])).rowCount)s=slugify(x.name)+'-'+(++i);const r=await q(`INSERT INTO products(category_id,name,slug,description,image_url,price,compare_price,purchase_price,wholesale_price,unit,stock,min_stock,active,featured) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[x.categoryId||null,x.name,s,x.description||null,x.imageUrl||null,money(x.price),x.comparePrice?money(x.comparePrice):null,money(x.purchasePrice),money(x.wholesalePrice),x.unit||'عدد',num(x.stock),num(x.minStock),x.active!==false,x.featured===true]);await q("INSERT INTO inventory_transactions(product_id,quantity,type,note) VALUES($1,$2,'initial',$3)",[r.rows[0].id,num(x.stock),'موجودی اولیه']);res.status(201).json(r.rows[0]);}catch(e){fail(res,e);}});
app.put('/api/admin/products/:id',auth,admin,async(req,res)=>{try{const x=req.body||{};const old=await q('SELECT stock FROM products WHERE id=$1',[req.params.id]);if(!old.rowCount)return res.status(404).json({error:'محصول پیدا نشد.'});const r=await q(`UPDATE products SET category_id=$1,name=$2,description=$3,image_url=$4,price=$5,compare_price=$6,purchase_price=$7,wholesale_price=$8,unit=$9,stock=$10,min_stock=$11,active=$12,featured=$13,updated_at=NOW() WHERE id=$14 RETURNING *`,[x.categoryId||null,x.name,x.description||null,x.imageUrl||null,money(x.price),x.comparePrice?money(x.comparePrice):null,money(x.purchasePrice),money(x.wholesalePrice),x.unit||'عدد',num(x.stock),num(x.minStock),x.active!==false,x.featured===true,req.params.id]);const delta=num(x.stock)-num(old.rows[0].stock);if(delta)await q("INSERT INTO inventory_transactions(product_id,quantity,type,note) VALUES($1,$2,'adjustment',$3)",[req.params.id,delta,'اصلاح موجودی توسط مدیر']);res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.delete('/api/admin/products/:id',auth,admin,async(req,res)=>{try{await q('UPDATE products SET active=false,updated_at=NOW() WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){fail(res,e);}});
app.get('/api/admin/categories',auth,admin,async(req,res)=>{try{res.json((await q('SELECT * FROM categories ORDER BY sort_order,name')).rows);}catch(e){fail(res,e);}});
app.post('/api/admin/categories',auth,admin,async(req,res)=>{try{const x=req.body||{};if(!x.name)return res.status(400).json({error:'نام دسته الزامی است.'});let s=slugify(x.name),i=1;while((await q('SELECT 1 FROM categories WHERE slug=$1',[s])).rowCount)s=slugify(x.name)+'-'+(++i);const r=await q('INSERT INTO categories(name,slug,image_url,active,sort_order) VALUES($1,$2,$3,$4,$5) RETURNING *',[x.name,s,x.imageUrl||null,x.active!==false,num(x.sortOrder)]);res.status(201).json(r.rows[0]);}catch(e){fail(res,e);}});
app.put('/api/admin/categories/:id',auth,admin,async(req,res)=>{try{const x=req.body||{},r=await q('UPDATE categories SET name=$1,image_url=$2,active=$3,sort_order=$4 WHERE id=$5 RETURNING *',[x.name,x.imageUrl||null,x.active!==false,num(x.sortOrder),req.params.id]);res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.delete('/api/admin/categories/:id',auth,admin,async(req,res)=>{try{await q('UPDATE categories SET active=false WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){fail(res,e);}});

// ---------- Admin prices/inventory/festivals ----------
app.get('/api/admin/prices',auth,admin,async(req,res)=>{try{res.json((await q(`SELECT p.id,p.name,p.unit,p.price,p.purchase_price,p.wholesale_price,COALESCE(d.price,p.price) daily_price,d.id daily_price_id,d.price_date,d.note FROM products p LEFT JOIN LATERAL (SELECT * FROM daily_prices WHERE product_id=p.id ORDER BY price_date DESC,created_at DESC LIMIT 1)d ON true WHERE p.active=true ORDER BY p.name`)).rows);}catch(e){fail(res,e);}});
app.put('/api/admin/prices/:productId',auth,admin,async(req,res)=>{try{const x=req.body||{},r=await q(`INSERT INTO daily_prices(product_id,price,purchase_price,wholesale_price,price_date,note) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[req.params.productId,money(x.price),money(x.purchasePrice),money(x.wholesalePrice),x.priceDate||null,x.note||null]);await q('UPDATE products SET price=$1,purchase_price=$2,wholesale_price=$3,updated_at=NOW() WHERE id=$4',[money(x.price),money(x.purchasePrice),money(x.wholesalePrice),req.params.productId]);res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.get('/api/admin/inventory',auth,admin,async(req,res)=>{try{res.json((await q(`SELECT id,name,stock,min_stock,unit,active FROM products ORDER BY active DESC,stock ASC,name`)).rows);}catch(e){fail(res,e);}});
app.post('/api/admin/inventory/adjust',auth,admin,async(req,res)=>{try{const x=req.body||{},qty=num(x.quantity);if(!x.productId||!qty)return res.status(400).json({error:'مقدار نامعتبر است.'});const type=x.type==='out'?'out':'in';const delta=type==='in'?qty:-qty;const r=await q('UPDATE products SET stock=GREATEST(0,stock+$1),updated_at=NOW() WHERE id=$2 RETURNING *',[delta,x.productId]);if(!r.rowCount)return res.status(404).json({error:'محصول پیدا نشد.'});await q('INSERT INTO inventory_transactions(product_id,quantity,type,note) VALUES($1,$2,$3,$4)',[x.productId,delta,type,x.note||'ثبت دستی']);res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.get('/api/admin/inventory/history',auth,admin,async(req,res)=>{try{res.json((await q(`SELECT i.*,p.name product_name FROM inventory_transactions i JOIN products p ON p.id=i.product_id ORDER BY i.created_at DESC LIMIT 200`)).rows);}catch(e){fail(res,e);}});
app.get('/api/admin/festivals',auth,admin,async(req,res)=>{try{const r=await q('SELECT * FROM festivals ORDER BY created_at DESC');res.json(r.rows);}catch(e){fail(res,e);}});
app.post('/api/admin/festivals',auth,admin,async(req,res)=>{try{const x=req.body||{};if(!x.name)return res.status(400).json({error:'نام جشنواره الزامی است.'});const r=await q('INSERT INTO festivals(name,description,discount_percent,start_at,end_at,image_url,active) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[x.name,x.description||null,x.discountPercent===null?null:num(x.discountPercent),x.startAt||null,x.endAt||null,x.imageUrl||null,x.active!==false]);res.status(201).json(r.rows[0]);}catch(e){fail(res,e);}});
app.put('/api/admin/festivals/:id',auth,admin,async(req,res)=>{try{const x=req.body||{},r=await q('UPDATE festivals SET name=$1,description=$2,discount_percent=$3,start_at=$4,end_at=$5,image_url=$6,active=$7 WHERE id=$8 RETURNING *',[x.name,x.description||null,x.discountPercent===null?null:num(x.discountPercent),x.startAt||null,x.endAt||null,x.imageUrl||null,x.active!==false,req.params.id]);res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.delete('/api/admin/festivals/:id',auth,admin,async(req,res)=>{try{await q('UPDATE festivals SET active=false WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){fail(res,e);}});

// ---------- Admin orders/customers/reports ----------
app.get('/api/admin/orders',auth,admin,async(req,res)=>{try{const status=req.query.status,a=[];let where='';if(status){a.push(status);where='WHERE o.status=$1';}res.json((await q(`SELECT o.*,u.name customer_name,u.phone,a.city,a.address FROM orders o LEFT JOIN users u ON u.id=o.user_id LEFT JOIN addresses a ON a.id=o.address_id ${where} ORDER BY o.created_at DESC`,a)).rows);}catch(e){fail(res,e);}});
app.get('/api/admin/orders/:id',auth,admin,async(req,res)=>{try{const o=await q(`SELECT o.*,u.name customer_name,u.phone,a.* FROM orders o LEFT JOIN users u ON u.id=o.user_id LEFT JOIN addresses a ON a.id=o.address_id WHERE o.id=$1`,[req.params.id]);if(!o.rowCount)return res.status(404).json({error:'سفارش پیدا نشد.'});const items=await q('SELECT * FROM order_items WHERE order_id=$1',[req.params.id]);res.json({order:o.rows[0],items:items.rows});}catch(e){fail(res,e);}});
app.put('/api/admin/orders/:id/status',auth,admin,async(req,res)=>{try{const allowed=['pending','processing','ready','completed','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'وضعیت نامعتبر است.'});const r=await q('UPDATE orders SET status=$1 WHERE id=$2 RETURNING *',[req.body.status,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'سفارش پیدا نشد.'});res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.put('/api/admin/orders/:id/payment',auth,admin,async(req,res)=>{try{const r=await q('UPDATE orders SET payment_status=$1 WHERE id=$2 RETURNING *',[req.body.status==='paid'?'paid':'unpaid',req.params.id]);res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.get('/api/admin/customers',auth,admin,async(req,res)=>{try{res.json((await q(`SELECT u.id,u.name,u.phone,u.active,u.created_at,COUNT(o.id)::int orders,COALESCE(SUM(CASE WHEN o.status<>'cancelled' THEN o.total ELSE 0 END),0) spent FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.created_at DESC`)).rows);}catch(e){fail(res,e);}});
app.put('/api/admin/customers/:id/status',auth,admin,async(req,res)=>{try{const r=await q('UPDATE users SET active=$1 WHERE id=$2 AND role=\'customer\' RETURNING id,active',[req.body.active!==false,req.params.id]);res.json(r.rows[0]);}catch(e){fail(res,e);}});
app.get('/api/admin/reports/sales',auth,admin,async(req,res)=>{try{const days=Math.min(365,Math.max(7,num(req.query.days)||30));res.json((await q(`SELECT created_at::date day,COUNT(*)::int orders,COALESCE(SUM(total) FILTER(WHERE status<>'cancelled'),0) sales FROM orders WHERE created_at>=CURRENT_DATE-$1::int GROUP BY created_at::date ORDER BY day DESC`,[days])).rows);}catch(e){fail(res,e);}});
app.get('/api/admin/reports/top-products',auth,admin,async(req,res)=>{try{res.json((await q(`SELECT oi.product_name,SUM(oi.quantity) quantity,SUM(oi.line_total) sales FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status<>'cancelled' GROUP BY oi.product_name ORDER BY sales DESC LIMIT 20`)).rows);}catch(e){fail(res,e);}});
app.get('/api/admin/reports/export-orders',auth,admin,async(req,res)=>{try{const r=await q(`SELECT o.id,o.created_at,o.status,o.payment_status,u.name customer_name,u.phone,o.subtotal,o.discount,o.shipping,o.total FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC`);const header='id,date,status,payment_status,customer,phone,subtotal,discount,shipping,total';const rows=r.rows.map(x=>[x.id,x.created_at.toISOString(),x.status,x.payment_status,x.customer_name||'',x.phone||'',x.subtotal,x.discount,x.shipping,x.total].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','));res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="varouk-orders.csv"');res.send('\ufeff'+header+'\n'+rows.join('\n'));}catch(e){fail(res,e);}});

// ---------- Settings ----------
app.get('/api/admin/settings',auth,admin,async(req,res)=>{try{res.json(Object.fromEntries((await q('SELECT key,value FROM settings ORDER BY key')).rows.map(x=>[x.key,x.value])));}catch(e){fail(res,e);}});
app.put('/api/admin/settings',auth,admin,async(req,res)=>{try{const allowed=['store_name','store_subtitle','phone','address','shipping_fee','min_order','instagram','telegram'];for(const k of allowed)if(Object.prototype.hasOwnProperty.call(req.body,k))await q('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,String(req.body[k]??'')]);res.json(Object.fromEntries((await q('SELECT key,value FROM settings')).rows.map(x=>[x.key,x.value])));}catch(e){fail(res,e);}});
app.put('/api/admin/profile/password',auth,admin,async(req,res)=>{try{const {currentPassword,newPassword}=req.body||{};const r=await q('SELECT password_hash FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount||!await bcrypt.compare(currentPassword,r.rows[0].password_hash||''))return res.status(400).json({error:'رمز فعلی صحیح نیست.'});if(String(newPassword||'').length<6)return res.status(400).json({error:'رمز جدید حداقل ۶ کاراکتر باشد.'});await q('UPDATE users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(newPassword,12),req.user.id]);res.json({ok:true});}catch(e){fail(res,e);}});

async function boot(){
 if(!process.env.DATABASE_URL){console.error('DATABASE_URL is not set');process.exit(1);}
 await pool.query(schema);
 const adminUser=String(process.env.ADMIN_USER||'').trim(),adminPass=String(process.env.ADMIN_PASSWORD||'');
 if(adminUser&&adminPass){const hash=await bcrypt.hash(adminPass,12);const e=await q("SELECT id FROM users WHERE phone=$1",[adminUser]);if(!e.rowCount)await q("INSERT INTO users(name,phone,password_hash,role,active) VALUES($1,$2,$3,'admin',true)",[process.env.ADMIN_NAME||'مدیر واروک',adminUser,hash]);else await q("UPDATE users SET password_hash=$1,role='admin',active=true WHERE phone=$2",[hash,adminUser]);}
 await q("INSERT INTO settings(key,value) VALUES ('store_name','هایپر پروتئین واروک'),('store_subtitle','خرید آسان و مطمئن'),('phone','09369817656'),('address','فولادشهر، اصفهان'),('shipping_fee','0'),('min_order','0') ON CONFLICT(key) DO NOTHING");
 app.listen(PORT,()=>console.log('Varouk platform running on '+PORT));
}
boot().catch(e=>{console.error(e);process.exit(1);});
